epochs = 20
number_of_gans = 5
switches = 8
examples = 100
smooth_zero = .1
smooth_one = .9
latent_dim = 50
x_train_size = None
dropout = .2
leaky_relu = 0.2
spectral_normalisation=False
weight_clipping=False
activation="tanh"